[package]
name = "ch-dict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cedict = "0.3.1"
lazy_static = "1.4.0"
radix_trie = "0.2.1"
